# Strategy parameters — auto-tuned by autoresearch loop
CSP_STRIKE_DELTA = 0.30
CSP_MIN_PREMIUM_PCT = 0.005
EARNINGS_CRUSH_MIN_IV_RANK = 50
BULL_PUT_SPREAD_WIDTH = 5
MOMENTUM_CONVICTION_THRESHOLD = 8.0
MOMENTUM_DELTA_TARGET = 0.30
MAX_DAYS_TO_EXPIRY = 45
MIN_DAYS_TO_EXPIRY = 21
