# SDS scoring weights — auto-tuned by autoresearch loop
WEIGHT_ZONING = 0.25
WEIGHT_SIZE = 0.20
WEIGHT_LOCATION = 0.20
WEIGHT_INFRASTRUCTURE = 0.15
WEIGHT_MARKET = 0.10
WEIGHT_FLOOD = 0.10
MIN_PARCEL_SIZE_ACRES = 0.5
MAX_FLOOD_ZONE_PCT = 0.50
MIN_SCORE_THRESHOLD = 6.0
