# Daily brief prompt structure — auto-tuned by autoresearch loop
REQUIRED_SECTIONS = ["regime", "positions", "signals", "news"]
MAX_BRIEF_LENGTH_CHARS = 3000
MIN_BRIEF_LENGTH_CHARS = 500
REGIME_SECTION_WEIGHT = 0.30
POSITIONS_SECTION_WEIGHT = 0.25
SIGNALS_SECTION_WEIGHT = 0.25
NEWS_SECTION_WEIGHT = 0.20
INCLUDE_WEEKLY_SUMMARY = False
INCLUDE_SECTOR_ROTATION = False
